In [21]:
from sklearn.metrics import classification_report, recall_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix
import sys
import numpy
from keras.models import load_model
import pickle
import os
import keras
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
default_model_path = '/home/dev2/Sanjana/stride/'

model = load_model(os.path.join(default_model_path,'binary_model_new.h5'))  # loading default model
tokenizer = pickle.load(open(os.path.join(default_model_path, 'word_tokenizer_binary_model.pickle'), 'rb'))
# encoder_level = pickle.load(open(os.path.join(default_model_path, 'levels_roclass.pickle'), 'rb'))
character_tokenizer = pickle.load(open(os.path.join(default_model_path, 'character_tokenizer_binary.pickle'), 'rb'))

char2idx = character_tokenizer
word_index = tokenizer.word_index
word_index['pad'] = 0
sent_max_len = 300
word_max_len = 10
N = 1
numpy.set_printoptions(threshold=sys.maxsize)


[nltk_data] Downloading package stopwords to /home/dev2/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [22]:
def intent_prediction(lista):
    empty_out=[]
    for i in lista:
        text=i
        text_tokens = word_tokenize(text)
        tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]
        text= (" ").join(tokens_without_sw)
        if 'list' not in str(type(text)):
            text = [text]
            print(text)
        print("Length in for batch predict class:", len(text))
        
        text[:] = [s.lower().replace(r'[^a-zA-Z\s]+|X{2,}', '') for s in text]
        text[:] = [re.sub(r'[^\w\s]', '', s) for s in text]
        sequences = tokenizer.texts_to_sequences(text)
        padded_sequences = keras.preprocessing.sequence.pad_sequences(maxlen=sent_max_len, sequences=sequences,
                                                                      value=word_index["pad"], padding='post',
                                                                      truncating='post')
        print("check")
        character_list = []
        for para in text:
            para_list = []
            for i in range(sent_max_len):
                word_seq = []
                for j in range(word_max_len):
                    try:
                        if char2idx.get(para[i][j]) is None:
                            raise Exception
                        word_seq.append(char2idx.get(para[i][j]))
                    except:
                        word_seq.append(char2idx.get("pad"))
                para_list.append(word_seq)
            character_list.append(para_list)
        print("1")
        character_list = np.array(character_list)
        predictions = model.predict([padded_sequences,
                                            character_list.reshape(character_list.shape[0], sent_max_len,
                                                                   word_max_len)])
        print(predictions)
        classes=["No","Yes"]
        empty_out.append((classes[int(predictions.argmax(axis=1))]))
    print(len(lista),len(empty_out))
    return empty_out


In [23]:
print("done")

done


In [24]:
import pandas as pd
df =pd.read_csv(r'test.csv')
df

Tags                                         paragraphs Unnamed: 2
0     No  I look forward to meeting you and learning abo...        NaN
1     No           We look forward to seeing you next week!        NaN
2     No               A quick question before our meeting.        NaN
3     No  After sunning and drinking all day we feasted ...        NaN
4     No              Also Tuesday, Kyle and Eric 1/2 hour.        NaN
5     No  Also, I made a change to paragraph 7 to includ...        NaN
6     No  As i was pondering the meeting last night goin...        NaN
7     No  As you become the responsible lawyer, first in...        NaN
8     No  As you know, last year's congress attracted ov...        NaN
9     No  As you may know, I am on the Compaq Computer b...        NaN
10    No  Ben is trying to set up a conference call with...        NaN
11    No                           Central Time, Wednesday.        NaN
12   Yes  Chris Calger wants the financing CP removed, a...        NaN
13    No  Christie is coming at 1:30 to meet the student...        NaN
14    No  Clickpaper.com will be out and live just befor...        NaN
15    No  Czy masz czas, by spotakc sie na obiad/lunch/k...        NaN
16    No               Darron is in Hawaii until next week.        NaN
17    No             Date: Tuesday, May 29 Time: 11:00 a.m.        NaN
18    No  Dear Keith, It was a pleasure to meet you and ...        NaN
19    No  Dev., TransCanada PipeLines IN-DEPTH SEMINARS ...        NaN
20    No  Diane, I will definitely show this to Ken, but...        NaN
21    No  Dr. Lay is unable to participate in the confer...        NaN
22    No    Drive carefully!! See you sometime this weekend        NaN
23    No  Enron Pres: Still Committed to Power Generatio...        NaN
24    No  Executive Committee Weekly Meeting Date: Monda...        NaN
25   Yes          FYI. Can you make a call tomorrow at 100?        NaN
26    No  Friday June 8, 2001 7:30 pm Tickets: $10 gener...        NaN
27    No  Get some rest and start studying for Wednesday...        NaN
28    No  Giuseppe did not receive the invitation to the...        NaN
29    No  Given our good, long-term relationship with UT...        NaN
..   ...                                                ...        ...
962  Yes  Please indicate below whether or not you plan ...        NaN
963  Yes  Please keep this news to yourself until next w...        NaN
964  Yes  Please let me know by tomorrow morning if you ...        NaN
965  Yes  Please let me know when you are ready to discuss.        NaN
966  Yes  Please let us know if you would like to attend...        NaN
967  Yes  Please protect Thursday afternoon, August 10th...        NaN
968  Yes  Please remove me from your email list for furt...        NaN
969  Yes  Please review the attached document to see if ...        NaN
970  Yes  Please review to see if I have made all of the...        NaN
971  Yes  Please send to Jeff for final review and one m...        NaN
972  Yes  Please set up a conference call for tomorrow, ...        NaN
973  Yes  Please tell Mike that I'm on a conference call...        NaN
974  Yes  Please, let me know if you want somebody from ...        NaN
975  Yes    Please, let me know the details of the dinners.        NaN
976  Yes                     Please, put it on my calendar.        NaN
977  Yes                     Please, put it on my schedule.        NaN
978  Yes                         Please, put on my calendar        NaN
979  Yes                        Please, put on my schedule.        NaN
980  Yes           Please, register me for this conference.        NaN
981  Yes  Please, set up a meeting with me, Nelson and V...        NaN
982  Yes            Shirley, Please, put it on my calendar.        NaN
983  Yes               Shirley, Please, put on my schedule.        NaN
984  Yes  Tana - can you fax me the final executed copie...        NaN
985  Yes      Why don't you try feeding her again at night?        NaN
986  Yes  Would you allow us

In [25]:
lista=df['paragraphs'].tolist()
output_list=intent_prediction(lista)
df['Predicted_Output']=output_list

['I look forward meeting learning successful business .']
Length in for batch predict class: 1
check
1
[[0.98066807 0.01933199]]
['We look forward seeing next week !']
Length in for batch predict class: 1
check
1
[[9.9983752e-01 1.6241612e-04]]
['A quick question meeting .']
Length in for batch predict class: 1
check
1
[[0.41632786 0.58367217]]
['After sunning drinking day feasted fleisch dinner ... eat , grilled bauchfleisch , steaks bratw ? rst ... WE ATE SOOO MUCH , DRANK SO MUCH THAT WE NEEDED IT , good greasy stuff .']
Length in for batch predict class: 1
check
1
[[9.9945897e-01 5.4099225e-04]]
['Also Tuesday , Kyle Eric 1/2 hour .']
Length in for batch predict class: 1
check
1
[[9.9981862e-01 1.8136378e-04]]
["Also , I made change paragraph 7 include technical bulletins Mitch 's request discuss call ."]
Length in for batch predict class: 1
check
1
[[0.9514244  0.04857565]]
['As pondering meeting last night going home car , I realized I forgot talk 2 people , including regulatory 

In [33]:
true_count=0
false_count=0
for row in df.itertuples():
    if row.Tags==row.Predicted_Output:
        true_count=true_count+1
    else:
        false_count=false_count+1
        
print("true_count",true_count)
print("false_count",false_count)
print("total_count",true_count+false_count)
accuracy=100*(true_count/(true_count+false_count))
print("Accuracy of model is ",accuracy)

true_count 778
false_count 214
total_count 992
Accuracy of model is  78.42741935483872


In [27]:
df.to_excel(r'/home/dev2/Sanjana/stride/output.xlsx')